FROM ubuntu:latest
# uses latest version of ubuntu as base image
RUN apt-get update && apt-get upgrade -y
# runs updates for currently installed softwares
CMD ["echo", "Hello, World!"]
# message to run upon build completion